// Port of the original Node compile/asm modules. Drives the vendored MWCC GC/2.0
// compiler (via wibo) and gekko objdump, then extracts each function's symbol +
// instruction count. The browser does the real instruction diff with
// objdiff-wasm against the raw object file, so we don't normalize asm here — we
// only need the symbol list, per-symbol instruction counts, and the object file.

use base64::Engine;
use regex::Regex;
use serde::Serialize;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;
use std::time::Duration;
use tokio::process::Command;
use tokio::time::timeout;

// Source language. Selects both the `-lang` flag and the source file extension
// (MWCC picks C vs C++ partly by extension), so it is NOT expressible via
// extra_flags alone.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Language {
    C,
    Cpp,
}

impl Language {
    pub fn parse(s: Option<&str>) -> Self {
        match s.map(str::trim) {
            Some("cpp") | Some("c++") | Some("cxx") => Language::Cpp,
            _ => Language::C,
        }
    }
    fn lang_flag(self) -> &'static str {
        match self {
            Language::C => "-lang=c",
            Language::Cpp => "-lang=c++",
        }
    }
    fn ext(self) -> &'static str {
        match self {
            Language::C => "c",
            Language::Cpp => "cpp",
        }
    }
}

// Optimization presets the frontend may request. A validated allow-list (rather
// than free-form `-O` strings) keeps the surface safe — `validate_opt` falls back
// to the default for anything unknown. `O4,p` reproduces today's behaviour.
pub const ALLOWED_OPT: &[&str] = &["O0", "O1", "O2,p", "O2,s", "O3,p", "O3,s", "O4,p", "O4,s"];
pub const DEFAULT_OPT: &str = "O4,p";

pub fn validate_opt(s: Option<&str>) -> String {
    match s.map(str::trim) {
        Some(v) if ALLOWED_OPT.contains(&v) => v.to_string(),
        _ => DEFAULT_OPT.to_string(),
    }
}

// One MWCC build. The registry (`COMPILERS`) is generated by build.rs from
// compilers.list so the binary, the fetch script, and the template generator all
// share one manifest. The same binary ships to every per-version Lambda; each
// Lambda's `MWCC_VERSION` env var selects its entry here.
pub struct Compiler {
    /// decomp.me id, e.g. "mwcc_247_92"; matched against the MWCC_VERSION env.
    pub id: &'static str,
    /// URL version segment, e.g. "247_92" -> /compile/mwcc/247_92/{action}.
    pub token: &'static str,
    /// Path to mwcceppc.exe under vendor/, e.g. "compiler/GC/2.0/mwcceppc.exe".
    pub rel_path: &'static str,
    /// Human label for /health.
    pub label: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/compilers_generated.rs"));

// GC MW 2.0 — the historical default. Owns the legacy flat routes, and the value
// every code path falls back to when MWCC_VERSION is unset (local dev, tests).
pub const DEFAULT_VERSION_ID: &str = "mwcc_247_92";

/// The compiler this Lambda is configured to run, from `MWCC_VERSION` (falling
/// back to the default). Looked up once per call — cheap over a linear scan of a
/// few dozen entries, and avoids any global init.
pub fn active_compiler() -> &'static Compiler {
    compiler_for(&std::env::var("MWCC_VERSION").unwrap_or_default())
}

/// Resolve a compiler by decomp.me id, falling back to the default for an
/// unset/unknown id. Split out from `active_compiler` so it's testable without
/// racing on the process-global `MWCC_VERSION` env var.
fn compiler_for(id: &str) -> &'static Compiler {
    COMPILERS
        .iter()
        .find(|c| c.id == id)
        .or_else(|| COMPILERS.iter().find(|c| c.id == DEFAULT_VERSION_ID))
        .expect("default compiler present in registry")
}

// Legacy body `compiler` field — superseded by the URL, ignored on versioned
// routes. Kept lenient for the flat routes the current frontend still calls
// (which send nothing, "GC/2.0", or "mwcc").
pub fn validate_compiler(s: Option<&str>) -> Result<(), String> {
    match s.map(str::trim) {
        None | Some("") | Some("mwcc") | Some("GC/2.0") => Ok(()),
        Some(other) => Err(format!(
            "Unsupported compiler '{other}'. This service compiles with MWCC; pick a \
             version via /compile/mwcc/<version>/<action>."
        )),
    }
}

/// True if `token` names a known MWCC build. Each version has its own Lambda +
/// literal route, so in practice the route already guarantees a valid token; this
/// guards direct/local invocation and yields a helpful error for typos.
pub fn validate_version(v: &str) -> Result<(), String> {
    let v = v.trim();
    if COMPILERS.iter().any(|c| c.token == v) {
        Ok(())
    } else {
        Err(format!("Unsupported mwcc version '{v}'."))
    }
}

// Assemble the compiler flag list. The opt token and `-lang` token occupy the
// SAME positions the old hardcoded set used, so the default C command line is
// byte-identical to before (no codegen drift). Peephole/scheduling are disabled
// by appending `-opt nopeephole` / `-schedule off` (both verified to match the
// in-source `#pragma peephole/scheduling off` the curriculum uses).
fn base_flags(language: Language, opt: &str, peephole: bool, schedule: bool) -> Vec<String> {
    let mut f: Vec<String> = [
        "-nodefaults", "-proc", "gekko", "-align", "powerpc", "-enum", "int", "-fp", "hardware",
        "-Cpp_exceptions", "off",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect();
    f.push(format!("-{opt}"));
    for s in ["-inline", "auto", "-maxerrors", "1", "-nosyspath", "-RTTI", "off", "-fp_contract", "on"] {
        f.push(s.to_string());
    }
    f.push(language.lang_flag().to_string());
    if !peephole {
        f.push("-opt".into());
        f.push("nopeephole".into());
    }
    if !schedule {
        f.push("-schedule".into());
        f.push("off".into());
    }
    f
}

const TYPES_PREAMBLE: &str = "typedef signed char s8;\n\
typedef signed short s16;\n\
typedef signed long s32;\n\
typedef signed long long s64;\n\
typedef unsigned char u8;\n\
typedef unsigned short u16;\n\
typedef unsigned long u32;\n\
typedef unsigned long long u64;\n\
typedef volatile u8 vu8;\n\
typedef volatile u16 vu16;\n\
typedef volatile u32 vu32;\n\
typedef volatile s8 vs8;\n\
typedef volatile s16 vs16;\n\
typedef volatile s32 vs32;\n\
typedef float f32;\n\
typedef double f64;\n\
typedef volatile f32 vf32;\n\
typedef volatile f64 vf64;\n\
typedef int BOOL;\n\
#define TRUE 1\n\
#define FALSE 0\n\
#ifndef NULL\n\
#define NULL 0\n\
#endif\n";

const TIMEOUT: Duration = Duration::from_millis(25_000);

fn vendor_base() -> PathBuf {
    let root = std::env::var("LAMBDA_TASK_ROOT").unwrap_or_else(|_| ".".into());
    PathBuf::from(root).join("vendor")
}

fn tool(env_key: &str, rel: &str) -> PathBuf {
    std::env::var(env_key)
        .map(PathBuf::from)
        .unwrap_or_else(|_| vendor_base().join(rel))
}

fn wibo() -> PathBuf {
    tool("WIBO", "toolchain/wibo")
}
/// The mwcceppc.exe this Lambda runs. `MWCC` env overrides for local dev/selftest;
/// otherwise the active compiler's vendored path (selected by MWCC_VERSION).
fn mwcc() -> PathBuf {
    std::env::var("MWCC")
        .map(PathBuf::from)
        .unwrap_or_else(|_| vendor_base().join(active_compiler().rel_path))
}
fn objdump() -> PathBuf {
    tool("OBJDUMP", "toolchain/binutils/powerpc-eabi-objdump")
}

#[derive(Serialize, Clone)]
pub struct Insn {
    pub mnemonic: String,
    #[serde(rename = "rawOperands")]
    pub raw_operands: String,
}

pub struct Outcome {
    pub ok: bool,
    pub diagnostics: String,
    pub instructions: Vec<Insn>,
    pub symbols: Vec<String>,
    pub obj_base64: Option<String>,
}

impl Outcome {
    fn fail(diagnostics: impl Into<String>, symbols: Vec<String>) -> Self {
        Outcome { ok: false, diagnostics: diagnostics.into(), instructions: Vec::new(), symbols, obj_base64: None }
    }
}

pub struct Request<'a> {
    pub code: &'a str,
    pub context: Option<&'a str>,
    pub symbol: &'a str,
    pub language: Language,
    /// Validated opt preset (e.g. "O4,p"); see `validate_opt`.
    pub opt: String,
    pub peephole: bool,
    pub schedule: bool,
    pub extra_flags: Vec<String>,
    pub with_types: bool,
}

enum RunErr {
    Timeout,
    Spawn(std::io::Error),
}

async fn run_cmd(program: &Path, args: &[String], cwd: Option<&Path>, dur: Duration) -> Result<std::process::Output, RunErr> {
    let mut cmd = Command::new(program);
    cmd.args(args).stdout(Stdio::piped()).stderr(Stdio::piped()).kill_on_drop(true);
    if let Some(c) = cwd {
        cmd.current_dir(c);
    }
    // Defense in depth: the toolchain (wibo/mwcc/objdump) never needs AWS
    // credentials, so strip them from the child's environment. That way, even if a
    // file-read vector ever reappears, `#include "/proc/self/environ"` on the
    // compiler process can't disclose the Lambda's role credentials.
    for k in [
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "AWS_SESSION_TOKEN",
        "AWS_SECURITY_TOKEN",
        "AWS_CONTAINER_CREDENTIALS_FULL_URI",
        "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI",
        "AWS_CONTAINER_AUTHORIZATION_TOKEN",
    ] {
        cmd.env_remove(k);
    }
    let child = cmd.spawn().map_err(RunErr::Spawn)?;
    match timeout(dur, child.wait_with_output()).await {
        Err(_) => Err(RunErr::Timeout),
        Ok(Ok(out)) => Ok(out),
        Ok(Err(e)) => Err(RunErr::Spawn(e)),
    }
}

fn unique_id() -> String {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{}-{}-{}", std::process::id(), nanos, n)
}

/// True if `code` or `context` contains an `#include` directive. Both are
/// caller-controlled on the playground endpoint, and an `#include` lets the
/// compiler read any file the sandbox can see (e.g. /proc/self/environ) and leak
/// it back through the error diagnostics — so both must be screened, not just code.
fn has_disallowed_include(code: &str, context: Option<&str>) -> bool {
    static INCLUDE_RE: OnceLock<Regex> = OnceLock::new();
    let re = INCLUDE_RE.get_or_init(|| Regex::new(r"(?m)^\s*#\s*include\b").unwrap());
    re.is_match(code) || context.is_some_and(|c| re.is_match(c))
}

/// Compile one translation unit and return the named function's symbol + count.
pub async fn compile(req: Request<'_>) -> Outcome {
    if has_disallowed_include(req.code, req.context) {
        return Outcome::fail(
            "#include is not allowed here. Everything you need (u8/s16/f32, and any \
             lesson-specific structs) is already in scope — just write the function.",
            Vec::new(),
        );
    }

    let mut preamble = String::new();
    if req.with_types {
        preamble.push_str(TYPES_PREAMBLE);
    }
    if let Some(ctx) = req.context {
        preamble.push_str(ctx);
        preamble.push('\n');
    }
    let source = format!("{}{}\n", preamble, req.code);
    let line_offset = preamble.matches('\n').count() as i64;

    // Reap scratch dirs left by invocations that were hard-killed (the 30s Lambda
    // wall / OOM) before their CleanupGuard could run. /tmp persists across
    // invocations on a warm container, so without this these leftovers pile up
    // until /tmp fills and this very write fails with ENOSPC.
    let mwcc_root = std::env::temp_dir().join("mwcc");
    sweep_stale_scratch(&mwcc_root);
    let dir = mwcc_root.join(unique_id());
    let c_file = dir.join(format!("u.{}", req.language.ext()));
    let o_file = dir.join("u.o");
    if let Err(e) = tokio::fs::create_dir_all(&dir).await {
        return Outcome::fail(format!("Could not create work dir: {e}"), Vec::new());
    }
    let _guard = CleanupGuard(dir.clone());

    if let Err(e) = tokio::fs::write(&c_file, source).await {
        return Outcome::fail(format!("Could not write source: {e}"), Vec::new());
    }

    let mut args: Vec<String> = vec![mwcc().to_string_lossy().into_owned()];
    args.extend(base_flags(req.language, &req.opt, req.peephole, req.schedule));
    args.extend(req.extra_flags.iter().cloned());
    args.push("-c".into());
    args.push(c_file.to_string_lossy().into_owned());
    args.push("-o".into());
    args.push(o_file.to_string_lossy().into_owned());

    let (combined, status_ok) = match run_cmd(&wibo(), &args, Some(&dir), TIMEOUT).await {
        Err(RunErr::Timeout) => {
            return Outcome::fail(
                "Compilation timed out (possible infinite loop in code generation).",
                Vec::new(),
            )
        }
        Err(RunErr::Spawn(_)) => (String::new(), false),
        Ok(out) => {
            let combined = format!(
                "{}{}",
                String::from_utf8_lossy(&out.stderr),
                String::from_utf8_lossy(&out.stdout)
            );
            (combined, out.status.success())
        }
    };

    if !o_file.exists() {
        if !status_ok {
            let diag = clean_diagnostics(&combined, line_offset);
            return Outcome::fail(if diag.is_empty() { "Compilation failed.".into() } else { diag }, Vec::new());
        }
        return Outcome::fail("Compiler produced no object file.", Vec::new());
    }

    let dump_args = ["-M", "gekko", "-drz", &o_file.to_string_lossy()].map(String::from).to_vec();
    let dump = match run_cmd(&objdump(), &dump_args, Some(&dir), TIMEOUT).await {
        Ok(out) => String::from_utf8_lossy(&out.stdout).into_owned(),
        Err(_) => {
            return Outcome::fail(
                "Your code compiled but produced too much output to disassemble. Try a smaller function.",
                Vec::new(),
            )
        }
    };

    let funcs = parse_objdump(&dump);
    let symbols: Vec<String> = funcs.iter().map(|(name, _)| name.clone()).collect();

    // The playground compiles arbitrary code with no fixed function in mind: an
    // empty symbol means "just give me the object + the symbol list" (the browser
    // enumerates and disassembles functions from the object via objdiff). A named
    // symbol keeps the lesson behaviour — it must exist or the compile is a miss.
    let instructions = if req.symbol.is_empty() {
        funcs.first().map(|(_, insns)| insns.clone()).unwrap_or_default()
    } else {
        match funcs.iter().find(|(name, _)| name == req.symbol).map(|(_, insns)| insns.clone()) {
            Some(insns) => insns,
            None => {
                let found = if symbols.is_empty() { "(none)".to_string() } else { symbols.join(", ") };
                let hint = if req.language == Language::Cpp {
                    format!(
                        "Function '{0}' not found in the compiled output. Found: {1}. \
                         In C++ the symbol is name-mangled — the function name, its enclosing \
                         class/namespace, and its parameter types all have to match exactly to \
                         produce '{0}'.",
                        req.symbol, found
                    )
                } else {
                    format!(
                        "Function '{0}' not found in the compiled output. Found: {1}. \
                         Make sure your function is named '{0}'.",
                        req.symbol, found
                    )
                };
                return Outcome::fail(hint, symbols);
            }
        }
    };

    let obj_base64 = match tokio::fs::read(&o_file).await {
        Ok(bytes) => base64::engine::general_purpose::STANDARD.encode(bytes),
        Err(e) => return Outcome::fail(format!("Could not read object file: {e}"), symbols),
    };

    Outcome { ok: true, diagnostics: String::new(), instructions, symbols, obj_base64: Some(obj_base64) }
}

/// Best-effort recursive cleanup of the per-compile scratch dir on scope exit.
struct CleanupGuard(PathBuf);
impl Drop for CleanupGuard {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// Reap stale scratch dirs under `root` left by invocations that died before
/// their CleanupGuard could run — e.g. the 30s Lambda timeout or an OOM kill
/// freezes the process mid-compile, so Drop never fires. The age guard (one
/// per-step TIMEOUT plus a wide margin) means we never remove a dir a compile is
/// still using: a warm container runs one invocation at a time, and no single
/// compile can outlive the 30s wall, so anything older is certainly abandoned.
/// Best-effort — every error (including a missing root on the first compile) is
/// ignored.
fn sweep_stale_scratch(root: &Path) {
    let max_age = TIMEOUT + Duration::from_secs(30);
    let now = std::time::SystemTime::now();
    let Ok(entries) = std::fs::read_dir(root) else { return };
    for entry in entries.flatten() {
        let abandoned = entry
            .metadata()
            .and_then(|m| m.modified())
            .ok()
            .and_then(|mtime| now.duration_since(mtime).ok())
            .map(|age| age > max_age)
            .unwrap_or(false);
        if abandoned {
            let _ = std::fs::remove_dir_all(entry.path());
        }
    }
}

fn parse_objdump(text: &str) -> Vec<(String, Vec<Insn>)> {
    static HEADER: OnceLock<Regex> = OnceLock::new();
    static INSN: OnceLock<Regex> = OnceLock::new();
    let header = HEADER.get_or_init(|| Regex::new(r"^[0-9a-fA-F]+\s+<([^>]+)>:").unwrap());
    // Reloc lines (`R_PPC...`) never match: the disasm bytes group requires hex pairs.
    let insn = INSN.get_or_init(|| Regex::new(r"^\s*[0-9a-fA-F]+:\s+(?:[0-9a-fA-F]{2}\s){1,4}\s*(.*)$").unwrap());

    let mut out: Vec<(String, Vec<Insn>)> = Vec::new();
    for line in text.split('\n') {
        if let Some(caps) = header.captures(line) {
            out.push((caps[1].to_string(), Vec::new()));
            continue;
        }
        let Some(current) = out.last_mut() else { continue };
        if let Some(caps) = insn.captures(line) {
            let rest = caps[1].trim();
            if rest.is_empty() {
                continue;
            }
            let sp = rest.find('\t').or_else(|| rest.find(' '));
            let (mnemonic, raw_operands) = match sp {
                Some(i) => (rest[..i].to_string(), rest[i..].trim().to_string()),
                None => (rest.to_string(), String::new()),
            };
            current.1.push(Insn { mnemonic, raw_operands });
        }
    }
    out
}

fn clean_diagnostics(text: &str, line_offset: i64) -> String {
    static MWCC_PATH: OnceLock<Regex> = OnceLock::new();
    static LINENUM: OnceLock<Regex> = OnceLock::new();
    static LEAD_HASH: OnceLock<Regex> = OnceLock::new();
    static NOISE: OnceLock<Vec<Regex>> = OnceLock::new();

    let mwcc_path = MWCC_PATH.get_or_init(|| Regex::new(r"\S*mwcc\S*u\.c(?:pp)?").unwrap());
    let linenum = LINENUM.get_or_init(|| Regex::new(r"\b(\d+)(\s*:)").unwrap());
    let lead_hash = LEAD_HASH.get_or_init(|| Regex::new(r"^#\s?").unwrap());
    let noise = NOISE.get_or_init(|| {
        [
            r"(?i)^wibo",
            r"(?i)User break, cancelled",
            r"(?i)Too many errors printed",
            r"(?i)^#{2,}\s*mwcceppc",
            r"^#\s*-{5,}",
            r"(?i)^#\s*File:",
            r"^\s*$",
        ]
        .iter()
        .map(|p| Regex::new(p).unwrap())
        .collect()
    });

    let text = mwcc_path.replace_all(text, "your code").replace('\r', "");

    let mut out: Vec<String> = Vec::new();
    for raw in text.split('\n') {
        if noise.iter().any(|re| re.is_match(raw)) {
            continue;
        }
        let remapped = linenum.replacen(raw, 1, |caps: &regex::Captures| {
            let n: i64 = caps[1].parse().unwrap_or(0);
            if n > line_offset {
                format!("{}{}", n - line_offset, &caps[2])
            } else {
                caps[0].to_string()
            }
        });
        out.push(lead_hash.replacen(&remapped, 1, "").into_owned());
    }

    let joined = out.join("\n");
    let trimmed = joined.trim();
    trimmed.chars().take(4000).collect()
}

/// Compiler banner — handy for /health. Prefixed with the active compiler's label
/// so each per-version Lambda's /health identifies which build it serves.
pub async fn compiler_version() -> String {
    let label = active_compiler().label;
    let args = vec![mwcc().to_string_lossy().into_owned(), "-version".to_string()];
    match run_cmd(&wibo(), &args, None, Duration::from_millis(15_000)).await {
        Ok(out) => {
            let combined = format!(
                "{}{}",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr)
            );
            let banner = combined.trim().lines().take(6).collect::<Vec<_>>().join("\n");
            if banner.is_empty() { label.to_string() } else { format!("{label}\n{banner}") }
        }
        Err(RunErr::Timeout) => format!("{label}: version probe timed out"),
        Err(RunErr::Spawn(e)) => format!("{label}: version probe failed: {e}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // The exact flag list the service hardcoded before C++ support. The default
    // C path MUST stay byte-identical to this, or existing reference targets stop
    // matching learners' objects.
    const LEGACY_C_FLAGS: &[&str] = &[
        "-nodefaults", "-proc", "gekko", "-align", "powerpc", "-enum", "int", "-fp", "hardware",
        "-Cpp_exceptions", "off", "-O4,p", "-inline", "auto", "-maxerrors", "1", "-nosyspath",
        "-RTTI", "off", "-fp_contract", "on", "-lang=c",
    ];

    #[test]
    fn default_c_flags_are_byte_identical_to_legacy() {
        let got = base_flags(Language::C, DEFAULT_OPT, true, true);
        assert_eq!(got, LEGACY_C_FLAGS, "default C flags drifted from the legacy set");
    }

    #[test]
    fn cpp_differs_only_in_lang_flag() {
        let c = base_flags(Language::C, DEFAULT_OPT, true, true);
        let cpp = base_flags(Language::Cpp, DEFAULT_OPT, true, true);
        assert_eq!(cpp.len(), c.len());
        for (a, b) in c.iter().zip(cpp.iter()) {
            if a == "-lang=c" {
                assert_eq!(b, "-lang=c++");
            } else {
                assert_eq!(a, b);
            }
        }
        assert_eq!(Language::Cpp.ext(), "cpp");
        assert_eq!(Language::C.ext(), "c");
    }

    #[test]
    fn opt_and_toggles_map_to_flags() {
        let f = base_flags(Language::C, "O2,s", false, false);
        assert!(f.contains(&"-O2,s".to_string()));
        assert!(!f.contains(&"-O4,p".to_string()));
        // disabled passes appended after the base set
        let joined = f.join(" ");
        assert!(joined.ends_with("-opt nopeephole -schedule off"), "got: {joined}");
    }

    #[test]
    fn validate_opt_rejects_arbitrary_input() {
        assert_eq!(validate_opt(Some("O3,p")), "O3,p");
        assert_eq!(validate_opt(Some("O9,evil")), DEFAULT_OPT);
        assert_eq!(validate_opt(Some("-rm -rf")), DEFAULT_OPT);
        assert_eq!(validate_opt(None), DEFAULT_OPT);
    }

    #[test]
    fn validate_compiler_is_lenient_for_legacy_field() {
        assert!(validate_compiler(None).is_ok());
        assert!(validate_compiler(Some("GC/2.0")).is_ok());
        assert!(validate_compiler(Some("mwcc")).is_ok());
        assert!(validate_compiler(Some("agbcc")).is_err());
    }

    // The registry is generated from compilers.list; sanity-check it loaded and
    // the default resolves (and that selection via MWCC_VERSION is wired).
    #[test]
    fn registry_loads_and_default_resolves() {
        assert!(COMPILERS.len() >= 20, "expected the full MWCC set, got {}", COMPILERS.len());
        assert!(COMPILERS.iter().any(|c| c.id == DEFAULT_VERSION_ID));
        // Tokens must be unique (they become literal URL segments / route keys).
        let mut tokens: Vec<&str> = COMPILERS.iter().map(|c| c.token).collect();
        tokens.sort_unstable();
        let n = tokens.len();
        tokens.dedup();
        assert_eq!(tokens.len(), n, "duplicate version token in compilers.list");
        // Default (env unset) is GC/2.0.
        assert_eq!(active_compiler().id, DEFAULT_VERSION_ID);
    }

    #[test]
    fn version_selection_picks_the_right_binary() {
        // The env value (MWCC_VERSION) selects which vendored exe a Lambda runs.
        let wii17 = compiler_for("mwcc_43_213");
        assert_eq!(wii17.token, "43_213");
        assert_eq!(wii17.rel_path, "compiler/Wii/1.7/mwcceppc.exe");
        let gc20 = compiler_for("mwcc_247_92");
        assert_eq!(gc20.rel_path, "compiler/GC/2.0/mwcceppc.exe");
        // Unknown / unset falls back to the default rather than panicking.
        assert_eq!(compiler_for("bogus").id, DEFAULT_VERSION_ID);
        assert_eq!(compiler_for("").id, DEFAULT_VERSION_ID);
    }

    #[test]
    fn validate_version_accepts_known_tokens_only() {
        assert!(validate_version("247_92").is_ok()); // GC/2.0
        assert!(validate_version("43_213").is_ok()); // Wii/1.7
        assert!(validate_version(" 247_92 ").is_ok());
        assert!(validate_version("9.9").is_err());
        assert!(validate_version("2.0").is_err()); // old token scheme is gone
    }

    #[test]
    fn include_guard_screens_code_and_context() {
        assert!(has_disallowed_include("#include <stdio.h>", None));
        assert!(has_disallowed_include("  #  include \"x.h\"", None));
        // The context bypass: an #include hidden in context must also be caught.
        assert!(has_disallowed_include("int f(){return 0;}", Some("#include \"/proc/self/environ\"")));
        // Legitimate code/context must pass.
        assert!(!has_disallowed_include("int f(){ return 0; }", Some("typedef struct { int x; } P;")));
        assert!(!has_disallowed_include("int g(int a){ return a; }", None));
    }

    #[test]
    fn language_parse() {
        assert!(matches!(Language::parse(Some("cpp")), Language::Cpp));
        assert!(matches!(Language::parse(Some("c++")), Language::Cpp));
        assert!(matches!(Language::parse(Some("c")), Language::C));
        assert!(matches!(Language::parse(None), Language::C));
    }
}
