// Generates the compiler registry (src include) from compilers.list, so the Rust
// binary, the fetch script, and the template generator all read ONE manifest and
// can't drift. Emits a `COMPILERS` slice keyed by decomp.me id; the running Lambda
// picks its entry via the MWCC_VERSION env var (see compile.rs::active_compiler).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = "compilers.list";
    println!("cargo:rerun-if-changed={manifest}");
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(manifest)
        .unwrap_or_else(|e| panic!("read {manifest}: {e}"));

    let mut rows = String::new();
    let mut count = 0usize;
    let mut seen_default = false;
    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split('|').collect();
        assert!(
            f.len() == 6,
            "compilers.list line {}: expected 6 pipe-delimited fields, got {}: {line:?}",
            lineno + 1,
            f.len()
        );
        // sha1 (f[4]) is consumed by fetch-toolchain.sh, not the binary.
        let (id, family, dir, token, label) = (f[0], f[1], f[2], f[3], f[5]);
        assert!(
            family == "GC" || family == "Wii",
            "compilers.list line {}: family must be GC or Wii, got {family:?}",
            lineno + 1
        );
        // Vendor layout mirrors the bundle: vendor/compiler/<family>/<dir>/mwcceppc.exe
        let rel_path = format!("compiler/{family}/{dir}/mwcceppc.exe");
        rows.push_str(&format!(
            "    Compiler {{ id: {id:?}, token: {token:?}, rel_path: {rel_path:?}, label: {label:?} }},\n"
        ));
        count += 1;
        if id == "mwcc_247_92" {
            seen_default = true;
        }
    }
    assert!(count > 0, "compilers.list has no entries");
    assert!(seen_default, "compilers.list must contain the default id mwcc_247_92");

    let out = format!(
        "// @generated by build.rs from compilers.list — do not edit.\n\
         pub static COMPILERS: &[Compiler] = &[\n{rows}];\n"
    );
    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("compilers_generated.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
